export const AGENDA = {
    ACTIONS: {
        ADD_OR_REPLACE_AGENDA: 'ADD_OR_REPLACE_AGENDA',
        RECEIVE_AGENDAS: 'RECEIVE_AGENDAS',
        SELECT_AGENDA: 'SELECT_AGENDA',
        REQUEST_AGENDAS: 'REQUEST_AGENDAS',
    },
    FILTER: {
        PLANNING_NOT_IN_AGENDA: 'PLANNING_NOT_IN_AGENDA',
        SELECT_AGENDA: 'SELECT_AGENDA',
    },
}
